# Generated by Django 4.0.3 on 2022-03-14 10:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('employee_manager', '0002_clockin_timeoff_alter_employee_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClockOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique Id for employee across organization', primary_key=True, serialize=False)),
                ('off_reason', models.CharField(max_length=200)),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='OffStarted')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='OffEnded')),
            ],
            options={
                'ordering': ['start_date', 'end_date'],
            },
        ),
        migrations.DeleteModel(
            name='TimeOff',
        ),
        migrations.AlterField(
            model_name='clockin',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique Id for clocking In', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='employeeinstance',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='employee_manager.employee'),
        ),
    ]
