# Generated by Django 4.0.3 on 2022-03-14 10:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('employee_manager', '0003_clockout_employeeinstance_delete_timeoff_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clockin',
            old_name='time',
            new_name='clock_in_time',
        ),
        migrations.AddField(
            model_name='clockout',
            name='clock_out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clockout',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique Id for clocking Out', primary_key=True, serialize=False),
        ),
    ]
