# Generated by Django 4.0.3 on 2022-03-15 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee_manager', '0006_alter_clockin_options_alter_clockout_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeinstance',
            name='given_off',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
