# Generated by Django 4.0.3 on 2022-03-15 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_manager', '0007_employeeinstance_given_off'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeinstance',
            options={'ordering': ['start_date', 'end_date'], 'permissions': (('can_end_off', 'Set the employee as returned from off period'),)},
        ),
    ]
